### ISSUE TITLE
npm start exception

### ISSUE THREAD

**Issue by achekulaev** [angular/angular-electron#13]
All other steps finished fine.

```
$ npm start
> @angular2/electron@1.0.0 start /Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master
> npm run demo
> @angular2/electron@1.0.0 demo /Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master
> npm run build && npm run build_demo && electron ./demo
> @angular2/electron@1.0.0 build /Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master
> npm run clean && tsc
> @angular2/electron@1.0.0 clean /Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master
> rimraf dist
> @angular2/electron@1.0.0 build_demo /Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master
> tsc typings/browser.d.ts demo/main.ts demo/app_ui.ts --module commonjs -t es5 --experimentalDecorators --emitDecoratorMetadata
App threw an error when running TypeError: Cannot read property 'prototype' of undefined
    at patchXHR (/Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master/node_modules/zone.js/dist/zone.js:112:63)
    at Object.<anonymous> (/Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master/node_modules/zone.js/dist/zone.js:80:2)
    at Object.Zone.Zone.zoneSpec._properties (/Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master/node_modules/zone.js/dist/zone.js:181:31)
    at __webpack_require__ (/Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master/node_modules/zone.js/dist/zone.js:20:30)
    at /Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master/node_modules/zone.js/dist/zone.js:40:18
    at Object.<anonymous> (/Users/alexei.chekulaev/Dropbox/Work/nw/angular-electron-master/node_modules/zone.js/dist/zone.js:43:10)
    at Module._compile (module.js:416:34)
    at Object.Module._extensions..js (module.js:425:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by trong** [comment]
the same problem

**Comment by jnhghy** [comment]
+1

**Comment by Quramy** [comment]
I think the code `import 'zone.js/dist/zone';` in demo/main.ts causes this error.
zone.js/dist/zone is a module for renderer process.
I rewrite it to `import 'zone.js/dist/zone-node';' and this error is fixed. 
I get some electron's BrowserWindow but it has been displaying 'Loading...'. There is no "Hello from Angular2 Electron" message. 
What's wrong?

**Comment by DanielGarciaMandillo** [comment]
You can modify the script "setup-demo" for this: zone.js@0.6.6 (delete ^ for download v0.6.6 instead v0.6.10)

Last version zone.js is 0.6.10 and the project maybe has not been update for that version yet.

**Comment by Quramy** [comment]
@DanielGarciaMandillo thx!

**Comment by soichih** [comment]
+1

**Comment by MartinMajewski** [comment]
How can you download zone.js@0.6.6 when the latest version is 0.3.4?
Are we speaking of different modules?

**Comment by ivodvb** [comment]
@MartinMajewski https://www.npmjs.com/package/zone.js
0.7.2 is the latest of 58 releases

**Comment by MartinMajewski** [comment]
Yeah... I was confused because I accidentally downloaded zone and not zone.js as package... -.-

**Comment by achekulaev** [comment]
Nothing seems to happen here. Closing the issue as I don't use the package anymore.
