### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by kazemihabib** [angular/angular-electron#15]
When I want to run the demo (arch linux):
gives me this error:

Uncaught Exception:
TypeError: Cannot read property 'prototype' of undefined
    at patchXHR (/run/media/habib/New Volume/projects/electron/angular-electron/node_modules/zone.js/dist/zone.js:113:63)
    at Object.<anonymous> (/run/media/habib/New Volume/projects/electron/angular-electron/node_modules/zone.js/dist/zone.js:81:2)
    at Object.Zone.Zone.zoneSpec._properties (/run/media/habib/New Volume/projects/electron/angular-electron/node_modules/zone.js/dist/zone.js:144:31)
    at __webpack_require__ (/run/media/habib/New Volume/projects/electron/angular-electron/node_modules/zone.js/dist/zone.js:20:30)
    at /run/media/habib/New Volume/projects/electron/angular-electron/node_modules/zone.js/dist/zone.js:40:18
    at Object.<anonymous> (/run/media/habib/New Volume/projects/electron/angular-electron/node_modules/zone.js/dist/zone.js:43:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by bgoscinski** [comment]
Duplicate of #13
