### ISSUE TITLE
Running the demo fails on Windows

### ISSUE THREAD

**Issue by maxdelemos** [angular/angular-electron#25]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.3.0
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @angular2/electron@1.0.0~prestart: @angular2/electron@1.0.0
6 silly lifecycle @angular2/electron@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle @angular2/electron@1.0.0~start: @angular2/electron@1.0.0
8 verbose lifecycle @angular2/electron@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle @angular2/electron@1.0.0~start: PATH: C:\Users\Usuario\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Usuario\Desktop\angular-electron\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\PuTTY\;C:\Program Files\nodejs\;C:\Users\Usuario\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Usuario\AppData\Roaming\npm
10 verbose lifecycle @angular2/electron@1.0.0~start: CWD: C:\Users\Usuario\Desktop\angular-electron
11 silly lifecycle @angular2/electron@1.0.0~start: Args: [ '/d /s /c', 'npm run demo' ]
12 silly lifecycle @angular2/electron@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle @angular2/electron@1.0.0~start: Failed to exec start script
14 verbose stack Error: @angular2/electron@1.0.0 start: `npm run demo`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Usuario\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Usuario\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @angular2/electron@1.0.0
16 verbose cwd C:\Users\Usuario\Desktop\angular-electron
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.0
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 2
23 error @angular2/electron@1.0.0 start: `npm run demo`
23 error Exit status 2
24 error Failed at the @angular2/electron@1.0.0 start script 'npm run demo'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the @angular2/electron package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run demo
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs @angular2/electron
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls @angular2/electron
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

```

**Comment by thattejada** [comment]
Same problem here, but i'm using Mac
